apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: norman-load
  region: eu-central-1
nodeGroups:
  - name: db
    desiredCapacity: 1
    instanceType: c6i.4xlarge
  - name: engine
    desiredCapacity: 3
    instanceType: c6i.xlarge