spring.datasource:
  url: jdbc:postgresql://localhost:5432/camunda
  username: camunda
  password: camunda
spring.h2.console.enabled: true
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
  default-serialization-format: application/json
  job-execution:
    enabled: true
    queue-capacity: 100
    core-pool-size: 10
    max-pool-size: 50
    lock-time-in-millis: 180000
    wait-time-in-millis: 2500
    max-jobs-per-acquisition: 50
    deployment-aware: false
  history-level: AUDIT
  client:
    base-url: http://localhost:${server.port}/engine-rest
    lock-duration: 20000
    async-response-timeout: 60000

management.endpoints.web.exposure.include: prometheus
server.port: 8080

sleeping-time-in-millis: 500