spring.datasource:
  url: ${SPRING_DATASOURCE_URL}
  username: ${SPRING_DATASOURCE_USERNAME}
  password: ${SPRING_DATASOURCE_PASSWORD}
  hikari:
    maximum-pool-size: 256
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
  default-serialization-format: application/json
  job-execution:
    # General
    enabled: true
    deployment-aware: false
    # JobExecutor
    queue-capacity: 2048
    core-pool-size: 8
    max-pool-size: 64
    keep-alive-seconds: 2500
    # JobAcquisition Configuration
    max-jobs-per-acquisition: 256
    lock-time-in-millis: 180000
    wait-time-in-millis: 5000
    max-wait: 30000
    backoff-time-in-millis: 0
    max-backoff: 0
    backoff-decrease-threshold: 100
    wait-increase-factor: 2
  history-level: NONE
  client:
    base-url: http://localhost:${server.port}/engine-rest
    lock-duration: 20000
    async-response-timeout: 60000
management.endpoints.web.exposure.include: prometheus
server.port: 8080

sleeping-time-in-millis: 100