{
 "title": "Performance Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Job Executor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job Executor Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "executor_active_threads{name=\"camundaTaskExecutor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Executor Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "executor_pool_size_threads{name=\"camundaTaskExecutor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Executor Pool Core Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "executor_pool_core_threads{name=\"camundaTaskExecutor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed Jobs per Second",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(executor_completed_tasks_total{name=\"camundaTaskExecutor\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum Completed Jobs per Second",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "rate(executor_completed_tasks_total{name=\"camundaTaskExecutor\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed Jobs Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "executor_completed_tasks_total{name=\"camundaTaskExecutor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "JDBC Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "jdbc_connections_min{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jdbc_connections_max{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hikari Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "hikaricp_connections{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hikari Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hikari Pending Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "hikaricp_connections_pending{job=\"springboot\"}"
    }
   ]
  },
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Disc Space Availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "disk_total_bytes{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "disk_free_bytes{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}