{{- if .Values.prometheusServiceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "c7-load-test.fullname" . }}
  labels: {{- include "c7-load-test.labels" . | nindent 4 }}
    {{- toYaml .Values.prometheusServiceMonitor.labels | nindent 4}}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "c7-load-test.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}

  endpoints:
    - honorLabels: true
      path: /actuator/prometheus
      port: http
      interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
  {{- end }}