{{- if .Values.prometheusServiceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "c7-load-test.fullname" . }}
  labels: {{- include "c7-load-test.labels" . | nindent 4 }}
    {{- toYaml .Values.prometheusServiceMonitor.labels | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- include "c7-load-test.labels" . | nindent 4 }}
  endpoints:
    - honorLabels: true
      path: /actuator/prometheus
      port: http
      interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
  {{- end }}